skip_checks:
  # - CKV_DOCKER_1  # Ensure a user is created in the Dockerfile
  - CKV_DOCKER_2  # Ensure that HEALTHCHECK instructions have been added
  # - CKV_DOCKER_3  # Ensure that COPY is used instead of ADD
