skip_checks:
  - CKV_DOCKER_1  # Ensure that a user for the container has been created
  - CKV_DOCKER_2  # Ensure that HEALTHCHECK instructions have been added to container images
  - CKV_DOCKER_3  # Ensure that COPY is used instead of ADD in Dockerfile

output: cli
quiet: true
compact: true