name: DevOps Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  devops-pipeline:
    runs-on: [s9]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Checkout Stage
        run: |
          echo "Checking out the repository. Please wait ............"
          sleep 1
      - name: Testing the Code
        run: |
          echo "Testing the code. Please wait ............"
          sleep 1
      - name: Scanning the Code
        run: |
          echo "Scanning the code. Please wait ............"
          sleep 1
      - name: Building the Code
        run: |
          echo "Building the code. Please wait ............"
          sleep 1
      - name: Pushing the Code to Artifactory
        run: |
          echo "Pushing the code to artifactory. Please wait ............"
          sleep 1
      - name: Deploying the Code
        run: |
          echo "Deploying the code. Please wait ............"
          sleep 1
      - name: Checking the Container State
        run: |
          echo "Checking the container state. Please wait ............"
          sleep 1
      - name: Clean Up
        run: |
          echo "Clean Up. Please wait ............"
          sleep 1
      - name: Success Message
        if: success()
        run: echo "Pipeline succeeded!"

      - name: Failure Message
        if: failure()
        run: echo "Pipeline failed!"